Rook
Robust-Sites/DiscordChessChallenger pull request #29
Opened 2022-07-07 22:37 UTC by Manny-Ventura

Added test conditions for Rook.

2022-07-07 23:18 UTC, jjmiranda8 requested changes
Great job making and using a helper function! The `return_array_of_numbers_except` function should be reworked a little. There is the `number` parameter that is passed into the function and the `numbers` array that you are looping through but then you use the variable name `number` to refer to instances in the array. I suggested renaming the parameter or the instance variable as you are looping through the array to make explicitly clear what number you are referring to. 

Some of your tests in _test_rook.py_ use `test_rook.x` as a variable within the function but then others use constants (integer literals) to denote the same thing. Definitely just use the object's _coordinate_ attribute throughout the tests for readability.

2022-07-08 00:25 UTC, jjmiranda8 approved these changes

2022-07-10 17:13 UTC, jjmiranda8 commented
Nice!

2022-07-10 17:22 UTC, Manny-Ventura reviewed
What does this do.

2022-07-10 17:50 UTC, merged